export const Data =[
  {
    created_at: '2019-05-28 19:58:30.711227',
    current_location: 'lira',
    delivery_price: '10000ugx',
    description: 'this product has two tube and more ',
    destination: 'kampala',
    parcel_id: 16,
    pickup: 'lira',
    receivers: 'ogwal emma',
    serial_no: 'CVFWD1WY',
    status: 'pending',
    user_id: 3,
    weight: 5
  },
  {
    created_at: '2019-05-28 11:10:37.577989',
    current_location: 'kampala',
    delivery_price: '8000ugx',
    description: 'is simply dummy text of the printing and typesetting industry. ',
    destination: 'lira',
    parcel_id: 15,
    pickup: 'kampala',
    receivers: 'anyatibrian',
    serial_no: 'GZJHHM1U',
    status: 'pending',
    user_id: 3,
    weight: 4
  },
  {
    created_at: '2019-05-28 11:10:23.595283',
    current_location: 'kampala',
    delivery_price: '8000ugx',
    description: 'is simply dummy text of the printing and typesetting industry. ',
    destination: 'lira',
    parcel_id: 14,
    pickup: 'kampala',
    receivers: 'anyatibrian',
    serial_no: '5EZ08UQB',
    status: 'pending',
    user_id: 3,
    weight: 4
  },
  {
    created_at: '2019-05-28 11:10:18.788783',
    current_location: 'kampala',
    delivery_price: '8000ugx',
    description: 'is simply dummy text of the printing and typesetting industry. ',
    destination: 'lira',
    parcel_id: 13,
    pickup: 'kampala',
    receivers: 'anyatibrian',
    serial_no: '8QI51SZP',
    status: 'pending',
    user_id: 3,
    weight: 4
  },
  {
    created_at: '2019-05-28 11:10:14.028513',
    current_location: 'kampala',
    delivery_price: '8000ugx',
    description: 'is simply dummy text of the printing and typesetting industry. ',
    destination: 'lira',
    parcel_id: 12,
    pickup: 'kampala',
    receivers: 'anyatibrian',
    serial_no: 'GF785GQ2',
    status: 'pending',
    user_id: 3,
    weight: 4
  },
  {
    created_at: '2019-05-28 11:10:08.246580',
    current_location: 'kampala',
    delivery_price: '8000ugx',
    description: 'is simply dummy text of the printing and typesetting industry. ',
    destination: 'lira',
    parcel_id: 11,
    pickup: 'kampala',
    receivers: 'anyatibrian',
    serial_no: 'VQYF36HM',
    status: 'pending',
    user_id: 3,
    weight: 4
  }];